-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('REGISTRATION', 'LOGIN', 'LOGOUT', 'FAILED_LOGIN', 'FAILED_AUTHORIZATION', 'USER_APPROVED', 'USER_DELETED', 'USER_PASSWORD_CHANGED', 'PERMISSION_CHANGED', 'MAP_UPDATED', 'MARKER_CREATED', 'MARKER_UPDATED', 'MARKER_DELETED', 'MARKER_RESTORED', 'MARKER_CLEANED_UP', 'MARKERS_EXPORTED');
ALTER TABLE "audit_events" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;

