export const TOWER_PROTECTION_DISTANCE_TILES = 25;
export const TOWER_PLACEMENT_DISTANCE_TILES = 50;
export const DELETED_MARKER_RETENTION_HOURS = 72;
export const MAX_NOTE_TEXT_LENGTH = 1000;
export const MAX_NAME_LENGTH = 80;
